### ISSUE TITLE
FRQ #1 - Rohan/Aarav

### ISSUE THREAD

**Issue by rjawesome** [rjawesome/CSASpringTri2#1]
# Rohan/Aarav
- [x] Implement FRQ1 in Spring project, use Spring Portfolio mvc/calendar for starter code
- [x] Enhance APCalendar.java to provide interesting facts on years, be creative and enhance/finish provided methods. For instance, use a random number or date to complete APCalendar day-of-week method.
  - Finds famous people's birthdays for a provided day & all unimplented methods from FRQ were completed w/ first day of 1970
- [x] Enhance APIs and @RESTController to work with the all POJOs and APCalendar.
  - dayInfo, yearInfo, and leapYears endpoints to access all methods in the APCalendar
- [x] Test APIs with Browser, Curl, or Postman. Illustrate or show tangibles.
![image](https://user-images.githubusercontent.com/16053597/202102110-62e38ae5-68e1-4e05-a1e0-43e0557935c9.png)
- [x] Test and use VSCode Debugger in development. Illustrate or show tangibles.
![image](https://user-images.githubusercontent.com/16053597/202102165-89fef267-500e-40df-a7a7-113cde7c2061.png)

**Comment by jm1021** [comment]
3
