### ISSUE TITLE
Aarav A/Rohan J Units 1-5 Blog

### ISSUE THREAD

**Issue by rjawesome** [rjawesome/CSASpringTri2#11]
Rohan's Blog: https://rohanj.dev/apcsa_fastpages/cb/2022/11/28/units15.html
- Unit 1: 1/1 (our presentation)
- [Unit 2: 1/1](https://rohanj.dev/apcsa_fastpages/2022/10/23/unit-2.html)
- [Unit 3: .9/1](https://kinerboi.github.io/myFirstRepopart2/2022/10/24/Unit3.html)
- [Unit 4: .8/1](https://rohanj.dev/apcsa_fastpages/2022/10/23/caesar.html)
- [Unit 5: .9/1](https://kinerboi.github.io/myFirstRepopart2/2022/10/20/Class.html)
- Total: 4.6/5

Aarav's Blog: https://aaravarora01.github.io/AaravArora-APCSA-Fastpages/jupyter/collegeboard%20learning/2022/11/29/1to5notebook.html

**Comment by aaravarora01** [comment]
5/5
Peer Review of Rohan: All work is completed at high quality
Code snippets are there for all terms, clearly above and beyond
Homework and Notes are all present and every term is used
Table of contents for easy navigation

**Comment by rjawesome** [comment]
5/5
Peer Review of Aarav: All work is completed at high quality
Code snippets for all units and good notes as well which link to frqs we learned before
All homeworks linked and easy to access

**Comment by rjawesome** [comment]
Graded/Complete
