### ISSUE TITLE
Nick/Bailey/Andrew FRQ 1 Review Ticket

### ISSUE THREAD

**Issue by nicm2** [rjawesome/CSASpringTri2#2]
- [x] Implement FRQ1 in Spring project, use Spring Portfolio mvc/calendar for starter code
- [x] Enhance APCalendar.java to provide interesting facts on years, be creative and enhance/finish provided methods. For instance, use a random number or date to complete APCalendar day-of-week method.
- ![image](https://user-images.githubusercontent.com/89167131/202531232-4fbbd87e-4737-4868-93b2-6369e937694d.png)
- [x]  Enhance APIs and @RestController to work with the all POJOs and APCalendar.
Json Formatting within the APIController
![image](https://user-images.githubusercontent.com/73082021/202772902-aefdd38a-8adb-4cd7-9604-24877f03a3b4.png)

Using year object
![image](https://user-images.githubusercontent.com/73082021/202773029-4cf0f5d9-7783-4584-a21d-ee39a6b2a18f.png)

- [x]  Test APIs with Browser, Curl, or Postman. Illustrate or show tangibles.
![image](https://user-images.githubusercontent.com/73082021/202771893-f0686a2d-0765-4f2b-a179-8e6bd831b345.png)

- [x]  Test and use VSCode Debugger in development. Illustrate or show tangibles.
![postmanAndDebug](https://user-images.githubusercontent.com/73082021/202655788-95112a33-a05c-4421-af33-31193ff23cd8.png)
![checkValidJson](https://user-images.githubusercontent.com/73082021/202655844-1b392298-9b1c-4675-adf0-3949ee729704.png)

![completedPostman](https://user-images.githubusercontent.com/73082021/202655850-da611568-9391-45c8-afa6-20d6cfdd8755.png)

**Comment by jm1021** [comment]
2.9 facts.
