### ISSUE TITLE
Aarav Review Ticket F/E and B/E - Quizlets for Classes

### ISSUE THREAD

**Issue by aaravarora01** [rjawesome/CSASpringTri2#23]
Self Grade: 3/3, Implemented Quizlet API Feature to fetch Quizlets from online and output terms and flashcards for students to study with on our site

### Working CLI Demo ###
![image](https://user-images.githubusercontent.com/16053597/217043635-18f88913-0330-4d73-9358-dd0ba12d09e6.png)

### AP CSA ###
AP CSA Terms: [Link](https://quizlet.com/76598385/ap-computer-science-a-flash-cards/)
AP CSA Ch 1-4 Terms: [Link](https://quizlet.com/151792590/ap-computer-science-a-chapter-1-4-review-flash-cards/)

### APUSH ###
Chs 7-12: [Link](https://quizlet.com/731039156/chapters-7-12-apush-flash-cards/?new)

### AP Physics ###
General Terms for Mechanics: [Link](https://quizlet.com/34703009/ap-physics-c-mechanics-terms-concepts-and-formulae-flash-cards/)

### AP English Language ###
Terms for MC/FRQ: [Link](https://quizlet.com/2176011/ap-language-terms-flash-cards/)
Vocabulary/Fallacies for MC: [Link](https://quizlet.com/262591/ap-english-language-vocabulary-flash-cards/)

### AP Gov ###
All Terms: [Link](https://quizlet.com/11505609/ap-government-review-set-flash-cards/)

### AP English Literature ###
Literary Terms: [Link](https://quizlet.com/163825/ap-english-literary-terms-flash-cards/)
Full List of Terms: [Link](https://quizlet.com/390627/ap-literature-terms-flash-cards/)

### AP Calc AB ###
Vocaulary Terms: [Link](https://quizlet.com/22312898/ap-calculus-ab-vocab-flash-cards/)

**Comment by NathanShih04** [comment]
Nathan grade for Aarav - 0.4/0.6

Did backend with fetching to get flash card terms and values that were preexistent. Injected these pulled values into use for future studiers. Demo tester method with Postman
