### ISSUE TITLE
Nick Peer Review Ticket 

### ISSUE THREAD

**Issue by nicm2** [rjawesome/CSASpringTri2#30]
- [x] .1 - Frontend UI demo.   UI takes inputs and passes them to an API and returns data from the backend to frontend.
- [x] .1 - Postman API Demo.  JSON Raw/Body formatted API passes inputs to backend and updates persistent table.
- [x] .1 - Java Demo - Object Creation.  Tester method that shows creation of Objects and outputs to Terminal, illustrate printing objects (hopefully using toString().
- [x] .1 - Java Demo with Postman or UI - All CRUD methods. Above was focused on Create and Read, this is focused on Update and Delete.

**Comment by Reem57** [comment]
Graded by Reem Ben Ishai
.4/.3 Had all the current requirements and crud methods and the website is well designed
