### ISSUE TITLE
Rohan Peer Review Ticket

### ISSUE THREAD

**Issue by rjawesome** [rjawesome/CSASpringTri2#31]
## Overall : .4/.6
# Expected
.1 - Frontend UI demo.   Quiz UI takes in the id of a flashcard setand returns a customized quiz
![image](https://user-images.githubusercontent.com/16053597/217901883-04346245-c44d-4774-9959-dafd926a04ea.png)
.1 - Postman API Demo.  JSON Raw/Body formatted API passes inputs to backend and updates persistent table.
![image](https://user-images.githubusercontent.com/16053597/217903646-293a7dc4-fc00-4041-b3d4-02f48da23d00.png)

.1 - Java Demo - Object Creation.  Tester method that shows creation of Objects and outputs to Terminal, illustrate printing objects (hopefully using toString().
![image](https://user-images.githubusercontent.com/16053597/217902187-661eceea-6930-4bb0-a690-82db497e11f1.png)

# Extra
.1 - Java Demo with Postman or UI - All CRUD methods.   Above was focused on Create and Read, this is focused on Update and Delete.
![image](https://user-images.githubusercontent.com/16053597/217902097-ba26a122-eb89-40ba-ae16-c2b7e90f0821.png)

**Comment by Gabrielboudreau** [comment]
.4/.3, evidence of progress in project, proper demos for application
